---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-sandbox
resources:
  - prometheus-rbac.yml
  - prometheus-instance.yml
  - prometheus-podmonitor.yml
  - prometheus-example-app-deployment.yml
  - blackbox-cm.yaml
  - blackbox-deployment.yaml
  - blackbox-svc.yaml
  - app-example-2.yaml
  - grafana-deployment.yaml
secretGenerator:
  - files:
      - prometheus-scrape-configs.yml
    name: prometheus-scrape-configs
    behavior: create
    options:
      disableNameSuffixHash: true
