---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-sandbox
resources:
  - prometheus-rbac.yml
  - prometheus-instance.yml
  - prometheus-podmonitor.yml
  - prometheus-example-app-deployment.yml
  - blackbox-cm.yml
  - blackbox-deployment.yml
  - blackbox-svc.yml
  - app-example-2.yml
  - grafana-deployment.yml
secretGenerator:
  - files:
      - prometheus-scrape-configs.yml
    name: prometheus-scrape-configs
    behavior: create
    options:
      disableNameSuffixHash: true
