apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prometheus
  labels:
    app: prometheus-simon
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-example-app  
  podMetricsEndpoints:
    - port: web
